- hosts: all
  become: yes
  become_method: sudo
  tasks:
   - name: Deleting existing script
     file:
       path: /tmp/syslog.sh
       state: absent
   - name: Copy Syslog Scripts
     copy:
       src: syslog.sh
       dest: /tmp/syslog.sh
       owner: root
       group: root
       mode: '0755'
   - name: Executinng Post-Check Script
     shell: |
       bash /tmp/syslog.sh postcheck
     register: postcheck
     ignore_errors: True
     no_log: True
